### ISSUE TITLE
otherwise

### ISSUE THREAD

**Issue by viscoze** [fantasyland/daggy#28]
Guys, what do you think if we add an option to cata matcher like `otherwise`, so that if there is no such appropriate matcher it call the function on the `otherwise` field. If there is no `otherwise` we can throw the error.

**Comment by davidchambers** [comment]
We could do this, although from my limited experience with Haskell I have the impression that the wild card match is considered dangerous.

**Comment by safareli** [comment]
For such cases I would just use `if else` with `Type.is(..)`, and i don't like idea of otherwise for `cata`


> from my limited experience with Haskell I have the impression that the wild card match is considered dangerous.

Yes `_` in `case` match is mostly not what you really want, as at some point you will add new node to your ADT and then because of some `_` you will miss a place which might need to be updated, when if you don't use `_` compiler will guide you to all places which need to be updated.

**Comment by SimonRichardson** [comment]
I think we should close this. I consider otherwise, wildcard, etc dangerous and I 100% agree with @safareli and this statement sums it up perfectly:

>  _ in case match is mostly not what you really want, as at some point you will add new node to your ADT and then because of some _ you will miss a place which might need to be updated

You're bypassing the strictness (as much as you can from this library, so excuse the flippantness), which is only going to bite you later on.

**Comment by SimonRichardson** [comment]
re-open if you think otherwise.
